[build]
  functions = "functions"
  publish = "client"
[template.environment]
  cl_name = 'Cloudinary Cloud Name'
  cl_key = 'Cloudinary API Key'
  cl_secret = 'Cloudinary API Secret'
  cl_ul_preset = 'Cloudinary Upload Preset Name (Unsigned)'
  cl_folder_name = 'Folder in Cloudinary Library'
  upload_key = 'Key Required to Upload'
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200